# Generated by Django 4.0.6 on 2022-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarzmodel',
            name='currency',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
