# Generated by Django 4.0.6 on 2022-07-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qarzapp', '0003_remove_qarzmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qarzmodel',
            name='currency',
        ),
    ]
