# Generated by Django 4.0.6 on 2022-07-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarzapp', '0004_remove_qarzmodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarzmodel',
            name='currency',
            field=models.BooleanField(default=False),
        ),
    ]
