# Generated by Django 4.0.6 on 2022-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarzapp', '0005_qarzmodel_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qarzmodel',
            name='reason',
        ),
        migrations.AlterField(
            model_name='qarzmodel',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], max_length=200),
        ),
        migrations.AlterField(
            model_name='qarzmodel',
            name='person',
            field=models.CharField(choices=[('ber', 'Qarz beruvchi'), ('ol', 'Qarz oluvchi')], max_length=200, null=True),
        ),
    ]
