# Generated by Django 4.0.6 on 2022-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarzapp', '0006_remove_qarzmodel_reason_alter_qarzmodel_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarzmodel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qarzmodel',
            name='person',
            field=models.CharField(choices=[('ber', 'Qarz berildi'), ('ol', 'Qarz olindi')], max_length=200, null=True),
        ),
    ]
