# Generated by Django 4.0.6 on 2022-07-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qarzapp', '0007_qarzmodel_name_alter_qarzmodel_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qarzmodel',
            old_name='person',
            new_name='condition',
        ),
    ]
